baseURL = "https://ora-guide.pages.dev/"
theme = "hugo-coder"
title = "Product Guide"

[params]
  avatarURL = "images/logo1.jpg"
  avatarSize = "40px"
  images = ""
  email = "contact.ora001@gmail.com"




[[menu.main]]
  name = "User Guide"
  url = "/user-guide-en/"
  weight = 1
[[menu.main]]
  name = "Installation"
  url = "/Installation-en/"
  weight = 2
[[menu.main]]
  name = "Videos"
  url = "/videos/"
  weight = 3
[[menu.main]]
  name = "Specs"
  url = "/specs/"
  weight = 4



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
