baseURL = "https://ora-guide.pages.dev/"
theme = "hugo-coder"
title = "Product Guide"

[params]
  avatarURL = "images/logo1.jpg"
  avatarSize = "40px"
  images = ""
  email = "contact.ora001@gmail.com"


[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Performance"
  url = "/performance/"
  weight = 2

[[menu.main]]
  name = "User Guide"
  url = "/user-guide-en/"
  weight = 3
[[menu.main]]
  name = "Installation"
  url = "/Installation-en/"
  weight = 4
[[menu.main]]
  name = "Specs"
  url = "/specs/"
  weight = 5
[[menu.main]]
  name = "Contact us"
  url = "/Contact/"
  weight = 6



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
